-- FASE 0 · 3.1 · campos candidatos a DATA DE ENTREGA (SPEC secao 3.1)
SELECT RTRIM(X3_ARQUIVO) ARQ, RTRIM(X3_CAMPO) CAMPO, RTRIM(X3_TITULO) TITULO,
       RTRIM(X3_DESCRIC) DESCRICAO, X3_TIPO TIPO, X3_TAMANHO TAM
FROM SX3010
WHERE D_E_L_E_T_ = ''
  AND X3_ARQUIVO IN ('SF2','SE1','SC5','SC9','SF1','SD1')
  AND (X3_CAMPO LIKE '%ENTR%' OR X3_TITULO LIKE '%ENTREG%' OR X3_DESCRIC LIKE '%ENTREG%')
ORDER BY X3_ARQUIVO, X3_CAMPO;
