-- FASE 0 · 3.1 (revisada) · a query do SPEC usa LIKE '%ENTREG%' (maiusculo).
-- O banco e CASE SENSITIVE -> titulos como "Dt. Entrega" NAO casavam. Refeito com COLLATE CI_AI.
SELECT DATABASEPROPERTYEX(DB_NAME(),'Collation') COLLATION_DO_BANCO;

SELECT RTRIM(X3_ARQUIVO) ARQ, RTRIM(X3_CAMPO) CAMPO, RTRIM(X3_TITULO) TITULO,
       RTRIM(X3_DESCRIC) DESCRICAO, X3_TIPO TIPO, X3_TAMANHO TAM
FROM SX3010
WHERE D_E_L_E_T_ = ''
  AND X3_ARQUIVO IN ('SF2','SE1','SC5','SC9','SF1','SD1','SD2')
  AND (X3_CAMPO    COLLATE Latin1_General_CI_AI LIKE '%ENTR%'
    OR X3_TITULO   COLLATE Latin1_General_CI_AI LIKE '%ENTREG%'
    OR X3_DESCRIC  COLLATE Latin1_General_CI_AI LIKE '%ENTREG%'
    OR X3_TITULO   COLLATE Latin1_General_CI_AI LIKE '%SAIDA%'
    OR X3_DESCRIC  COLLATE Latin1_General_CI_AI LIKE '%SAIDA%')
ORDER BY X3_ARQUIVO, X3_CAMPO;
