-- FASE 0 · 3.2 · taxa de preenchimento da DATA DE ENTREGA
-- Campos confirmados na 3.1: SF2.F2_DTENTR e SE1.E1_DTSAIDA (ambos D/8, varchar(8) YYYYMMDD)
DECLARE @DATADE CHAR(8), @DATAATE CHAR(8);
SET @DATADE = '20260801'; SET @DATAATE = '20260918';

-- (a) SF2 no periodo do SPEC
SELECT 'SF2 01/08-18/09' JANELA, COUNT(*) TOTAL,
       SUM(CASE WHEN F2_DTENTR <> '' THEN 1 ELSE 0 END) COM_ENTREGA,
       CAST(100.0*SUM(CASE WHEN F2_DTENTR <> '' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT
FROM SF2010 WHERE D_E_L_E_T_='' AND F2_EMISSAO BETWEEN @DATADE AND @DATAATE;

-- (b) SF2 por filial, 12 meses
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);
SELECT 'SF2 12 meses' JANELA, F2_FILIAL FILIAL, COUNT(*) TOTAL,
       SUM(CASE WHEN F2_DTENTR <> '' THEN 1 ELSE 0 END) COM_ENTREGA,
       CAST(100.0*SUM(CASE WHEN F2_DTENTR <> '' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT
FROM SF2010 WHERE D_E_L_E_T_='' AND F2_EMISSAO >= @DE12
GROUP BY F2_FILIAL ORDER BY TOTAL DESC;

-- (c) SE1: so titulos originados de NF de venda (E1_TIPO padrao 'NF '/'FAT'); mede E1_DTSAIDA
SELECT 'SE1 01/08-18/09' JANELA, COUNT(*) TOTAL,
       SUM(CASE WHEN E1_DTSAIDA <> '' THEN 1 ELSE 0 END) COM_ENTREGA,
       CAST(100.0*SUM(CASE WHEN E1_DTSAIDA <> '' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT
FROM SE1010 WHERE D_E_L_E_T_='' AND E1_EMISSAO BETWEEN @DATADE AND @DATAATE;

-- (d) COMBINADO por NF: regra de precedencia do SPEC (SF2 -> SE1 -> vazio)
SELECT 'COMBINADO por NF 01/08-18/09' JANELA,
       COUNT(*) NF_TOTAL,
       SUM(CASE WHEN F2.F2_DTENTR <> '' THEN 1 ELSE 0 END) SO_SF2,
       SUM(CASE WHEN F2.F2_DTENTR = '' AND E1.DT_SE1 IS NOT NULL THEN 1 ELSE 0 END) RESGATADA_PELA_SE1,
       SUM(CASE WHEN F2.F2_DTENTR <> '' OR E1.DT_SE1 IS NOT NULL THEN 1 ELSE 0 END) COM_ENTREGA_FINAL,
       CAST(100.0*SUM(CASE WHEN F2.F2_DTENTR <> '' OR E1.DT_SE1 IS NOT NULL THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_FINAL
FROM SF2010 F2
LEFT JOIN (SELECT E1_FILIAL F, E1_NUM N, E1_PREFIXO P, MAX(E1_DTSAIDA) DT_SE1
           FROM SE1010 WHERE D_E_L_E_T_='' AND E1_DTSAIDA <> ''
           GROUP BY E1_FILIAL, E1_NUM, E1_PREFIXO) E1
       ON E1.F = F2.F2_FILIAL AND E1.N = F2.F2_DOC AND E1.P = F2.F2_SERIE
WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO BETWEEN @DATADE AND @DATAATE;
