-- FASE 0 · 3.6 volumetria 12 meses + evolucao do preenchimento da data de entrega
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);

-- (a) NF de SAIDA por mes (SF2) + % com data de entrega
SELECT LEFT(F2_EMISSAO,6) ANOMES, COUNT(*) NF_SAIDA,
       SUM(CASE WHEN F2_DTENTR <> '' THEN 1 ELSE 0 END) COM_DTENTR,
       CAST(100.0*SUM(CASE WHEN F2_DTENTR <> '' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_ENTREGA,
       CAST(SUM(F2_VALFAT) AS DECIMAL(18,2)) VALOR
FROM SF2010 WHERE D_E_L_E_T_='' AND F2_EMISSAO >= @DE12
GROUP BY LEFT(F2_EMISSAO,6) ORDER BY ANOMES;

-- (b) NF de ENTRADA tipo D (devolucao) por mes
SELECT LEFT(F1_EMISSAO,6) ANOMES, COUNT(*) NF_DEVOLUCAO,
       CAST(SUM(F1_VALBRUT) AS DECIMAL(18,2)) VALOR
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
GROUP BY LEFT(F1_EMISSAO,6) ORDER BY ANOMES;
