-- FASE 0 · 3.2 · MOTIVO DE DEVOLUCAO: preenchimento real de cada candidato
-- Universo = NF de entrada tipo D (devolucao) nos ultimos 12 meses.
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);

-- (a) candidatos no CABECALHO da propria devolucao (SF1)
SELECT COUNT(*) NF_DEV_12M,
  SUM(CASE WHEN LTRIM(RTRIM(F1_MOTRET))  <> '' THEN 1 ELSE 0 END) F1_MOTRET,
  SUM(CASE WHEN LTRIM(RTRIM(F1_MOTIVO))  <> '' THEN 1 ELSE 0 END) F1_MOTIVO,
  SUM(CASE WHEN LTRIM(RTRIM(F1_MENNOTA)) <> '' THEN 1 ELSE 0 END) F1_MENNOTA,
  SUM(CASE WHEN LTRIM(RTRIM(F1_MENPAD))  <> '' THEN 1 ELSE 0 END) F1_MENPAD,
  SUM(CASE WHEN DATALENGTH(ISNULL(F1_HISTRET,0x)) > 0 THEN 1 ELSE 0 END) F1_HISTRET,
  SUM(CASE WHEN LTRIM(RTRIM(F1_DEVMERC)) <> '' THEN 1 ELSE 0 END) F1_DEVMERC
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12;

-- (b) candidatos no PEDIDO DE VENDA original (caminho do SPEC: SD1->SD2->SC5)
SELECT COUNT(DISTINCT F1.F1_DOC+'|'+F1.F1_SERIE+'|'+F1.F1_FORNECE+'|'+F1.F1_LOJA) NF_DEV_COM_VINCULO,
  SUM(CASE WHEN LTRIM(RTRIM(ISNULL(C5.C5_MENNOTA,''))) <> '' THEN 1 ELSE 0 END) C5_MENNOTA_ITENS,
  SUM(CASE WHEN LTRIM(RTRIM(ISNULL(C5.C5_OBS,'')))     <> '' THEN 1 ELSE 0 END) C5_OBS_ITENS,
  SUM(CASE WHEN LTRIM(RTRIM(ISNULL(C5.C5_COMENT,'')))  <> '' THEN 1 ELSE 0 END) C5_COMENT_ITENS,
  COUNT(*) ITENS_DEV
FROM SD1010 D1
JOIN SF1010 F1 ON F1.F1_FILIAL=D1.D1_FILIAL AND F1.F1_DOC=D1.D1_DOC AND F1.F1_SERIE=D1.D1_SERIE
             AND F1.F1_FORNECE=D1.D1_FORNECE AND F1.F1_LOJA=D1.D1_LOJA AND F1.D_E_L_E_T_=''
LEFT JOIN SD2010 D2 ON D2.D2_FILIAL=D1.D1_FILIAL AND D2.D2_DOC=D1.D1_NFORI AND D2.D2_SERIE=D1.D1_SERIORI
             AND D2.D2_ITEM=D1.D1_ITEMORI AND D2.D_E_L_E_T_=''
LEFT JOIN SC5010 C5 ON C5.C5_FILIAL=D2.D2_FILIAL AND C5.C5_NUM=D2.D2_PEDIDO AND C5.D_E_L_E_T_=''
WHERE D1.D_E_L_E_T_='' AND F1.F1_TIPO='D' AND F1.F1_EMISSAO >= @DE12;

-- (c) o vinculo NF devolucao -> NF origem existe? (D1_NFORI preenchido)
SELECT COUNT(*) ITENS_DEV,
       SUM(CASE WHEN LTRIM(RTRIM(D1.D1_NFORI)) <> '' THEN 1 ELSE 0 END) COM_NFORI,
       CAST(100.0*SUM(CASE WHEN LTRIM(RTRIM(D1.D1_NFORI)) <> '' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT
FROM SD1010 D1
JOIN SF1010 F1 ON F1.F1_FILIAL=D1.D1_FILIAL AND F1.F1_DOC=D1.D1_DOC AND F1.F1_SERIE=D1.D1_SERIE
             AND F1.F1_FORNECE=D1.D1_FORNECE AND F1.F1_LOJA=D1.D1_LOJA AND F1.D_E_L_E_T_=''
WHERE D1.D_E_L_E_T_='' AND F1.F1_TIPO='D' AND F1.F1_EMISSAO >= @DE12;
