-- FASE 0 · 3.2 · o texto livre contem MOTIVO? Amostra dos valores mais frequentes.
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);

-- (a) F1_MENNOTA da propria devolucao: top 20 conteudos
SELECT TOP 20 LEFT(LTRIM(RTRIM(F1_MENNOTA)),90) TEXTO_F1_MENNOTA, COUNT(*) QTD
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
  AND LTRIM(RTRIM(F1_MENNOTA)) <> ''
GROUP BY LEFT(LTRIM(RTRIM(F1_MENNOTA)),90) ORDER BY QTD DESC;

-- (b) quantos F1_MENNOTA tem palavra-chave de motivo real
SELECT COUNT(*) NF_DEV_COM_TEXTO,
  SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%avari%'
             OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%quebrad%'
             OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%recus%'
             OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%defeit%'
             OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%troca%'
             OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%arrepend%'
             OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%divergen%'
             OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%garantia%'
        THEN 1 ELSE 0 END) COM_PALAVRA_DE_MOTIVO
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
  AND LTRIM(RTRIM(F1_MENNOTA)) <> '';

-- (c) C5_MENNOTA (pedido de venda original): top 10 — verificar se e boilerplate
SELECT TOP 10 LEFT(LTRIM(RTRIM(C5.C5_MENNOTA)),90) TEXTO_C5_MENNOTA, COUNT(*) QTD
FROM SD1010 D1
JOIN SF1010 F1 ON F1.F1_FILIAL=D1.D1_FILIAL AND F1.F1_DOC=D1.D1_DOC AND F1.F1_SERIE=D1.D1_SERIE
             AND F1.F1_FORNECE=D1.D1_FORNECE AND F1.F1_LOJA=D1.D1_LOJA AND F1.D_E_L_E_T_=''
JOIN SD2010 D2 ON D2.D2_FILIAL=D1.D1_FILIAL AND D2.D2_DOC=D1.D1_NFORI AND D2.D2_SERIE=D1.D1_SERIORI
             AND D2.D2_ITEM=D1.D1_ITEMORI AND D2.D_E_L_E_T_=''
JOIN SC5010 C5 ON C5.C5_FILIAL=D2.D2_FILIAL AND C5.C5_NUM=D2.D2_PEDIDO AND C5.D_E_L_E_T_=''
WHERE D1.D_E_L_E_T_='' AND F1.F1_TIPO='D' AND F1.F1_EMISSAO >= @DE12
  AND LTRIM(RTRIM(C5.C5_MENNOTA)) <> ''
GROUP BY LEFT(LTRIM(RTRIM(C5.C5_MENNOTA)),90) ORDER BY QTD DESC;
