-- FASE 0 · 3.2 · cobertura e TAXONOMIA REAL do motivo (padrao "MOTIVO DEV: <causa>" em F1_MENNOTA)
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);

-- (a) cobertura: quantas devolucoes trazem o prefixo MOTIVO
SELECT COUNT(*) NF_DEV_12M,
  SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 1 ELSE 0 END) COM_MOTIVO,
  CAST(100.0*SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 1 ELSE 0 END)
       /NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_COBERTURA
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12;

-- (b) cobertura por mes (a pratica e recente ou consolidada?)
SELECT LEFT(F1_EMISSAO,6) ANOMES, COUNT(*) NF_DEV,
  SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 1 ELSE 0 END) COM_MOTIVO,
  CAST(100.0*SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 1 ELSE 0 END)
       /NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
GROUP BY LEFT(F1_EMISSAO,6) ORDER BY ANOMES;

-- (c) taxonomia: texto apos "MOTIVO DEV" ate a "OS"/"/" -> causa normalizada
WITH DEV AS (
  SELECT F1_DOC, F1_SERIE, F1_MENNOTA,
         LTRIM(REPLACE(REPLACE(REPLACE(
           SUBSTRING(F1_MENNOTA, PATINDEX('%MOTIVO%', F1_MENNOTA COLLATE Latin1_General_CI_AI)+6, 60)
         ,'DEV.:',''),'DEV:',''),'DEV','')) RESTO
  FROM SF1010
  WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
    AND F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%'
)
SELECT CAUSA, COUNT(*) QTD FROM (
  SELECT LTRIM(RTRIM(
    CASE WHEN CHARINDEX('OS', RESTO COLLATE Latin1_General_CI_AI) > 0
         THEN LEFT(RESTO, CHARINDEX('OS', RESTO COLLATE Latin1_General_CI_AI)-1) ELSE RESTO END
  )) CAUSA FROM DEV) X
GROUP BY CAUSA ORDER BY QTD DESC;
