-- FASE 0 · 3.2 · taxonomia NORMALIZADA + cobertura na janela real do ETL (120 dias, SPEC 5)
DECLARE @DE120 CHAR(8); SET @DE120 = CONVERT(CHAR(8), DATEADD(DAY,-120,GETDATE()), 112);

SELECT '120 dias' JANELA, COUNT(*) NF_DEV,
  SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 1 ELSE 0 END) COM_MOTIVO,
  CAST(100.0*SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 1 ELSE 0 END)
       /NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE120;

-- taxonomia normalizada por palavra-chave (12 meses) — base do motivos_map.yaml da Fase 2
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);
SELECT CAUSA_NORMALIZADA, COUNT(*) QTD,
       CAST(100.0*COUNT(*)/SUM(COUNT(*)) OVER () AS DECIMAL(5,1)) PCT
FROM (
  SELECT CASE
    WHEN M LIKE '%CONSERT%'                      THEN 'CONSERTO'
    WHEN M LIKE '%ACORDO%' OR M LIKE '%NEGOCIAC%' THEN 'ACORDO_COMERCIAL'
    WHEN M LIKE '%DEFEIT%'                       THEN 'DEFEITO_FUNCIONAL'
    WHEN M LIKE '%AVARI%' OR M LIKE '%DANIFIC%' OR M LIKE '%MOLHAD%' OR M LIKE '%SINISTR%' THEN 'AVARIA'
    WHEN M LIKE '%RECUS%' OR M LIKE '%DESISTENC%' OR M LIKE '%ARREPEND%' THEN 'RECUSA_CLIENTE'
    WHEN M LIKE '%AGENDO%' OR M LIKE '%AGENDA%'  THEN 'NAO_AGENDOU'
    WHEN M LIKE '%LOGISTIC%' OR M LIKE '%REGIAO NORTE%' OR M LIKE '%N EXPEDID%'
      OR M LIKE '%NAO RECEBID%' OR M LIKE '%FALTA NA CARGA%' THEN 'LOGISTICO'
    WHEN M LIKE '%CUBAGEM%' OR M LIKE '%VOLTAGEM%' OR M LIKE '%DIVERGEN%' THEN 'ERRO_PEDIDO'
    WHEN M LIKE '%FEIRA%' OR M LIKE '%MOSTRUARI%' THEN 'RETORNO_EVENTO'
    ELSE 'NAO_CLASSIFICADO' END CAUSA_NORMALIZADA
  FROM (SELECT F1_MENNOTA COLLATE Latin1_General_CI_AI M FROM SF1010
        WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
          AND F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%') A
) B GROUP BY CAUSA_NORMALIZADA ORDER BY QTD DESC;
