-- FASE 0 · 3.3 (refinado) + 3.4 CFOPs de devolucao
-- NOTA (excecao consciente a regra do D_E_L_E_T_): as consultas a SF3010 abaixo NAO filtram
-- D_E_L_E_T_ de proposito — o evento de cancelamento precisa ser visto mesmo quando a linha
-- correspondente foi excluida. E exatamente o que a SPEC 3.3 pede. A SF2 e consultada com o
-- D_E_L_E_T_ EXPOSTO como coluna (DEL), para medir o comportamento, nunca como filtro oculto.
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);

-- (a) cancelamento SO de notas de SAIDA (F3_ENTRADA vazio = saida)
SELECT 'cancelamentos de SAIDA 12m' TESTE, COUNT(*) TOTAL_NF_CANC,
       SUM(CASE WHEN F2.F2_DOC IS NULL THEN 1 ELSE 0 END) SEM_LINHA_SF2,
       SUM(CASE WHEN F2.DEL='*' THEN 1 ELSE 0 END) SF2_DELETADA,
       SUM(CASE WHEN F2.DEL='' THEN 1 ELSE 0 END) SF2_AINDA_ATIVA
FROM (SELECT DISTINCT F3_FILIAL FIL, F3_NFISCAL NF, F3_SERIE SER
      FROM SF3010 WHERE F3_DTCANC >= @DE12 AND LTRIM(RTRIM(ISNULL(F3_ENTRADA,'')))='') C
LEFT JOIN (SELECT F2_FILIAL FIL, F2_DOC, F2_SERIE, D_E_L_E_T_ DEL FROM SF2010) F2
       ON F2.FIL=C.FIL AND F2.F2_DOC=C.NF AND F2.F2_SERIE=C.SER;

-- (b) as 12 ainda ativas sao erro de processo ou cancelamento parcial? amostra
SELECT TOP 12 C.NF, C.SER, F2.F2_EMISSAO, F2.F2_VALFAT, C.DTCANC
FROM (SELECT DISTINCT F3_FILIAL FIL, F3_NFISCAL NF, F3_SERIE SER, F3_DTCANC DTCANC
      FROM SF3010 WHERE F3_DTCANC >= @DE12 AND LTRIM(RTRIM(ISNULL(F3_ENTRADA,'')))='') C
JOIN SF2010 F2 ON F2.F2_FILIAL=C.FIL AND F2.F2_DOC=C.NF AND F2.F2_SERIE=C.SER AND F2.D_E_L_E_T_=''
ORDER BY C.DTCANC DESC;

-- (c) CFOPs reais de devolucao (SPEC 3.4)
SELECT D1_CF CFOP, COUNT(*) QTD_ITENS,
       COUNT(DISTINCT D1.D1_DOC+'|'+D1.D1_SERIE) QTD_NF,
       CAST(SUM(D1.D1_TOTAL) AS DECIMAL(18,2)) VALOR
FROM SD1010 D1
JOIN SF1010 F1 ON F1.F1_FILIAL=D1.D1_FILIAL AND F1.F1_DOC=D1.D1_DOC AND F1.F1_SERIE=D1.D1_SERIE
             AND F1.F1_FORNECE=D1.D1_FORNECE AND F1.F1_LOJA=D1.D1_LOJA AND F1.D_E_L_E_T_=''
WHERE D1.D_E_L_E_T_='' AND F1.F1_TIPO='D' AND F1.F1_EMISSAO >= @DE12
GROUP BY D1_CF ORDER BY QTD_ITENS DESC;
