-- FASE 0 · 3.3 · como separar SAIDA x ENTRADA na SF3? (a premissa F3_ENTRADA='' falhou)
SELECT RTRIM(X3_CAMPO) CAMPO, RTRIM(X3_TITULO) TITULO, RTRIM(X3_DESCRIC) DESCRICAO, X3_TIPO, X3_TAMANHO
FROM SX3010 WHERE D_E_L_E_T_='' AND X3_ARQUIVO='SF3'
  AND (X3_CAMPO COLLATE Latin1_General_CI_AI LIKE '%ENTRA%'
    OR X3_CAMPO COLLATE Latin1_General_CI_AI LIKE '%SAIDA%'
    OR X3_CAMPO COLLATE Latin1_General_CI_AI LIKE '%CFO%'
    OR X3_CAMPO COLLATE Latin1_General_CI_AI LIKE '%TIPO%'
    OR X3_CAMPO COLLATE Latin1_General_CI_AI LIKE '%CANC%')
ORDER BY X3_CAMPO;

-- amostra de valores de F3_ENTRADA nos cancelados
SELECT TOP 5 F3_NFISCAL, F3_SERIE, '['+ISNULL(F3_ENTRADA,'<null>')+']' F3_ENTRADA, F3_EMISSAO, F3_CFO, F3_DTCANC
FROM SF3010 WHERE F3_DTCANC <> '' ORDER BY F3_DTCANC DESC;
