-- FASE 0 · 3.5 · a view ja entrega NF + cliente + valor + devolucao? · e o CANAL (secao 4)
SELECT COUNT(*) VIEW_EXISTE FROM sys.views WHERE name='VW_AZ_FATURAMENTO_ANALITICO_NOVO';

SELECT c.name COLUNA, t.name TIPO
FROM sys.columns c JOIN sys.types t ON t.user_type_id=c.user_type_id
WHERE c.object_id=OBJECT_ID('VW_AZ_FATURAMENTO_ANALITICO_NOVO') ORDER BY c.column_id;

-- a view distingue venda de devolucao?
SELECT ORIGEM, COUNT(*) LINHAS, CAST(SUM(FATURAMENTO) AS DECIMAL(18,2)) VALOR
FROM VW_AZ_FATURAMENTO_ANALITICO_NOVO
WHERE [DT NF] >= CONVERT(CHAR(8), DATEADD(MONTH,-3,GETDATE()), 112)
GROUP BY ORIGEM;

-- CANAL B2B/B2C: candidatos no cadastro de clientes
SELECT A1_TIPO, COUNT(*) QTD FROM SA1010 WHERE D_E_L_E_T_='' GROUP BY A1_TIPO ORDER BY QTD DESC;
SELECT TOP 8 A1_GRPVEN, COUNT(*) QTD FROM SA1010 WHERE D_E_L_E_T_='' GROUP BY A1_GRPVEN ORDER BY QTD DESC;

-- TRANSPORTADORA na SF2 (campo do modelo da Fase 1)
SELECT TOP 5 F2_TRANSP, COUNT(*) QTD FROM SF2010
WHERE D_E_L_E_T_='' AND F2_EMISSAO >= CONVERT(CHAR(8), DATEADD(MONTH,-3,GETDATE()), 112)
GROUP BY F2_TRANSP ORDER BY QTD DESC;
