-- FASE 0 · 3.2 · SF2.F2_DTENTR x SE1.E1_DTSAIDA divergem na MESMA NF?
-- (a precedencia "SF2 primeiro" do SPEC so e segura se as fontes concordarem)
DECLARE @DE CHAR(8), @ATE CHAR(8); SET @DE='20260201'; SET @ATE='20260918';
WITH SE1U AS (
  SELECT E1_FILIAL FIL, E1_NUM NUM, E1_PREFIXO PRE, MAX(E1_DTSAIDA) DT
  FROM SE1010 WHERE D_E_L_E_T_='' AND E1_DTSAIDA <> ''
  GROUP BY E1_FILIAL, E1_NUM, E1_PREFIXO
)
SELECT COUNT(*) NF_COM_AS_DUAS,
  SUM(CASE WHEN F2.F2_DTENTR = S.DT THEN 1 ELSE 0 END) IGUAIS,
  SUM(CASE WHEN F2.F2_DTENTR <> S.DT THEN 1 ELSE 0 END) DIVERGENTES,
  CAST(100.0*SUM(CASE WHEN F2.F2_DTENTR <> S.DT THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_DIVERG,
  AVG(CASE WHEN F2.F2_DTENTR <> S.DT
      THEN DATEDIFF(DAY, CONVERT(DATE,F2.F2_DTENTR,112), CONVERT(DATE,S.DT,112)) END) MEDIA_DIAS_SE1_MENOS_SF2
FROM SF2010 F2
JOIN SE1U S ON S.FIL=F2.F2_FILIAL AND S.NUM=F2.F2_DOC AND S.PRE=F2.F2_SERIE
WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO BETWEEN @DE AND @ATE AND F2.F2_DTENTR <> '';

-- distribuicao da diferenca
WITH SE1U AS (
  SELECT E1_FILIAL FIL, E1_NUM NUM, E1_PREFIXO PRE, MAX(E1_DTSAIDA) DT
  FROM SE1010 WHERE D_E_L_E_T_='' AND E1_DTSAIDA <> '' GROUP BY E1_FILIAL, E1_NUM, E1_PREFIXO
)
SELECT CASE WHEN D = 0 THEN 'iguais'
            WHEN D BETWEEN 1 AND 7 THEN 'SE1 1-7 dias depois'
            WHEN D > 7 THEN 'SE1 mais de 7 dias depois'
            WHEN D BETWEEN -7 AND -1 THEN 'SE1 1-7 dias antes'
            ELSE 'SE1 mais de 7 dias antes' END FAIXA, COUNT(*) QTD
FROM (SELECT DATEDIFF(DAY, CONVERT(DATE,F2.F2_DTENTR,112), CONVERT(DATE,S.DT,112)) D
      FROM SF2010 F2 JOIN SE1U S ON S.FIL=F2.F2_FILIAL AND S.NUM=F2.F2_DOC AND S.PRE=F2.F2_SERIE
      WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO BETWEEN @DE AND @ATE AND F2.F2_DTENTR <> '') X
GROUP BY CASE WHEN D = 0 THEN 'iguais'
            WHEN D BETWEEN 1 AND 7 THEN 'SE1 1-7 dias depois'
            WHEN D > 7 THEN 'SE1 mais de 7 dias depois'
            WHEN D BETWEEN -7 AND -1 THEN 'SE1 1-7 dias antes'
            ELSE 'SE1 mais de 7 dias antes' END
ORDER BY QTD DESC;
