-- FASE 0 · 3.2 · E1_DTSAIDA e ENTREGA ou SAIDA? Comparar com a EMISSAO da NF.
DECLARE @DE CHAR(8), @ATE CHAR(8); SET @DE='20260201'; SET @ATE='20260918';
WITH SE1U AS (
  SELECT E1_FILIAL FIL, E1_NUM NUM, E1_PREFIXO PRE, MAX(E1_DTSAIDA) DT
  FROM SE1010 WHERE D_E_L_E_T_='' AND E1_DTSAIDA <> '' GROUP BY E1_FILIAL,E1_NUM,E1_PREFIXO
), B AS (
  SELECT F2.F2_DOC, F2.F2_EMISSAO EMIS, NULLIF(F2.F2_DTENTR,'') SF2_ENTR, S.DT SE1_DT,
         DATEDIFF(DAY, CONVERT(DATE,F2.F2_EMISSAO,112), CONVERT(DATE,S.DT,112)) D_EMIS_SE1,
         CASE WHEN F2.F2_DTENTR<>'' THEN DATEDIFF(DAY, CONVERT(DATE,F2.F2_EMISSAO,112), CONVERT(DATE,F2.F2_DTENTR,112)) END D_EMIS_SF2
  FROM SF2010 F2 JOIN SE1U S ON S.FIL=F2.F2_FILIAL AND S.NUM=F2.F2_DOC AND S.PRE=F2.F2_SERIE
  WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO BETWEEN @DE AND @ATE
)
SELECT COUNT(*) NF,
  SUM(CASE WHEN D_EMIS_SE1 = 0 THEN 1 ELSE 0 END) SE1_IGUAL_A_EMISSAO,
  CAST(100.0*SUM(CASE WHEN D_EMIS_SE1=0 THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_SE1_IGUAL_EMISSAO,
  AVG(D_EMIS_SE1) MEDIA_DIAS_EMISSAO_ATE_SE1,
  AVG(D_EMIS_SF2) MEDIA_DIAS_EMISSAO_ATE_SF2DTENTR,
  SUM(CASE WHEN D_EMIS_SE1 < 0 THEN 1 ELSE 0 END) SE1_ANTES_DA_EMISSAO,
  SUM(CASE WHEN D_EMIS_SF2 < 0 THEN 1 ELSE 0 END) SF2ENTR_ANTES_DA_EMISSAO
FROM B;
