-- FASE 0 (revisao 21/09, apos o relatorio "Cancelamento P_Entrada 2026" do Silvio)
-- 1) F1_FORMUL='S' = nota de ENTRADA EMITIDA PELA AMVOX (o relatorio); ''= devolucao emitida pelo cliente
-- 2) a medicao anterior de motivo usou LIKE '%MOTIVO%' e PERDEU a convencao "MOT:" / "MOT.:"
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);

SELECT CASE WHEN F1_FORMUL='S' THEN 'S = emitida pela AMVOX' ELSE '  = emitida pelo cliente' END ORIGEM_NF,
  COUNT(*) NF_DEV,
  SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 1 ELSE 0 END) PADRAO_ANTIGO,
  SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT%' THEN 1 ELSE 0 END) PADRAO_AMPLO,
  CAST(100.0*SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT%' THEN 1 ELSE 0 END)
       /NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_AMPLO
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
GROUP BY CASE WHEN F1_FORMUL='S' THEN 'S = emitida pela AMVOX' ELSE '  = emitida pelo cliente' END;

-- mesma quebra na janela do ETL (120 dias)
DECLARE @DE120 CHAR(8); SET @DE120 = CONVERT(CHAR(8), DATEADD(DAY,-120,GETDATE()), 112);
SELECT CASE WHEN F1_FORMUL='S' THEN 'S = AMVOX' ELSE '  = cliente' END ORIGEM_NF, COUNT(*) NF_DEV,
  SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT%' THEN 1 ELSE 0 END) COM_MOTIVO,
  CAST(100.0*SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT%' THEN 1 ELSE 0 END)
       /NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE120
GROUP BY CASE WHEN F1_FORMUL='S' THEN 'S = AMVOX' ELSE '  = cliente' END;
