-- FASE 0 · precisao do padrao amplo: o que casa com %MOT% mas NAO com %MOTIVO%?
DECLARE @DE120 CHAR(8); SET @DE120 = CONVERT(CHAR(8), DATEADD(DAY,-120,GETDATE()), 112);
SELECT TOP 15 LEFT(LTRIM(RTRIM(F1_MENNOTA)),95) TEXTO, COUNT(*) QTD
FROM SF1010
WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE120
  AND F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT%'
  AND F1_MENNOTA COLLATE Latin1_General_CI_AI NOT LIKE '%MOTIVO%'
GROUP BY LEFT(LTRIM(RTRIM(F1_MENNOTA)),95) ORDER BY QTD DESC;

-- falsos positivos plausiveis
SELECT SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTOR%' THEN 1 ELSE 0 END) TEM_MOTOR,
       SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%REMOT%' THEN 1 ELSE 0 END) TEM_REMOTO,
       SUM(CASE WHEN F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT[ .:]%'
                  OR F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOTIV%' THEN 1 ELSE 0 END) MARCADOR_REAL,
       COUNT(*) TOTAL_COM_MOT
FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE120
  AND F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT%';
