-- FASE 0 (revisao 21/09) · cobertura da data de entrega do FINANCEIRO (E1_DTSAIDA)
-- no universo JA DECIDIDO: todas as filiais, SOMENTE faturamento (VALFAT>0), remessa fora.
DECLARE @DE CHAR(8), @ATE CHAR(8); SET @DE='20260201'; SET @ATE='20260918';
WITH SE1U AS (
  SELECT E1_FILIAL FIL, E1_NUM NUM, E1_PREFIXO PRE, MAX(E1_DTSAIDA) DT
  FROM SE1010 WHERE D_E_L_E_T_='' AND E1_DTSAIDA <> '' GROUP BY E1_FILIAL,E1_NUM,E1_PREFIXO
)
SELECT LEFT(F2.F2_EMISSAO,6) ANOMES, COUNT(*) NF_FATURAMENTO,
  SUM(CASE WHEN S.DT IS NOT NULL THEN 1 ELSE 0 END) COM_DT_FINANCEIRO,
  CAST(100.0*SUM(CASE WHEN S.DT IS NOT NULL THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_SE1,
  SUM(CASE WHEN F2.F2_DTENTR <> '' THEN 1 ELSE 0 END) COM_DT_LOGISTICA,
  CAST(100.0*SUM(CASE WHEN F2.F2_DTENTR <> '' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_SF2
FROM SF2010 F2
LEFT JOIN SE1U S ON S.FIL=F2.F2_FILIAL AND S.NUM=F2.F2_DOC AND S.PRE=F2.F2_SERIE
WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO BETWEEN @DE AND @ATE AND F2.F2_VALFAT > 0
GROUP BY LEFT(F2.F2_EMISSAO,6) ORDER BY ANOMES;
