-- FASE 0 (revisao 21/09) · decisao do Silvio: "listar o que encontramos na base" (sem taxonomia fixa).
-- Extrai a causa das DUAS convencoes achadas, nas DUAS origens (AMVOX e cliente), 12 meses.
DECLARE @DE12 CHAR(8); SET @DE12 = CONVERT(CHAR(8), DATEADD(MONTH,-12,GETDATE()), 112);
WITH BASE AS (
  SELECT F1_MENNOTA M, CASE WHEN F1_FORMUL='S' THEN 'AMVOX' ELSE 'CLIENTE' END ORIG
  FROM SF1010 WHERE D_E_L_E_T_='' AND F1_TIPO='D' AND F1_EMISSAO >= @DE12
    AND F1_MENNOTA COLLATE Latin1_General_CI_AI LIKE '%MOT%'
), CORTE AS (
  -- pega o texto DEPOIS do marcador (MOTIVO / MOT. / MOT:)
  SELECT ORIG, LTRIM(SUBSTRING(M,
      PATINDEX('%MOT%', M COLLATE Latin1_General_CI_AI)
      + CASE WHEN M COLLATE Latin1_General_CI_AI LIKE '%MOTIVO%' THEN 6 ELSE 3 END, 70)) T
  FROM BASE
), LIMPO AS (
  SELECT ORIG, LTRIM(RTRIM(
    REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(T,'DEV.:',''),'DEV:',''),'DEV',''),'.:',''),':','')
  )) T FROM CORTE
), SEMREF AS (  -- remove o sufixo de OS/CHAMADO para agrupar a causa
  SELECT ORIG, LTRIM(RTRIM(CASE
    WHEN CHARINDEX('OS',  T COLLATE Latin1_General_CI_AI) > 1 THEN LEFT(T, CHARINDEX('OS',  T COLLATE Latin1_General_CI_AI)-1)
    WHEN CHARINDEX('CH',  T COLLATE Latin1_General_CI_AI) > 1 THEN LEFT(T, CHARINDEX('CH',  T COLLATE Latin1_General_CI_AI)-1)
    WHEN CHARINDEX('-',   T) > 1 THEN LEFT(T, CHARINDEX('-', T)-1)
    ELSE T END)) CAUSA FROM LIMPO
)
SELECT CAUSA, SUM(CASE WHEN ORIG='AMVOX' THEN 1 ELSE 0 END) NF_AMVOX,
       SUM(CASE WHEN ORIG='CLIENTE' THEN 1 ELSE 0 END) NF_CLIENTE, COUNT(*) TOTAL
FROM SEMREF WHERE CAUSA <> '' GROUP BY CAUSA HAVING COUNT(*) >= 3 ORDER BY TOTAL DESC;
