-- FASE 0 · a GWU tem dados? amarra na NF? como se compara com SF2/SE1?
SELECT 'tabelas' T, name TABELA FROM sys.tables WHERE name LIKE 'GWU%' OR name LIKE 'GWF%' ORDER BY name;

SELECT 'volume GWU010' T, COUNT(*) LINHAS,
       SUM(CASE WHEN GWU_DTENT <> '' THEN 1 ELSE 0 END) COM_DT_ENTREGA,
       SUM(CASE WHEN GWU_DTPENT <> '' THEN 1 ELSE 0 END) COM_PREVISAO,
       SUM(CASE WHEN LTRIM(RTRIM(GWU_XMOTAT)) <> '' THEN 1 ELSE 0 END) COM_MOTIVO_ATRASO,
       MIN(NULLIF(GWU_DTENT,'')) PRIMEIRA, MAX(NULLIF(GWU_DTENT,'')) ULTIMA
FROM GWU010 WHERE D_E_L_E_T_='';

-- amarracao com a NF de faturamento (GWU_NRDC = numero do documento)
DECLARE @DE CHAR(8); SET @DE='20260201';
SELECT 'cobertura sobre NF de faturamento' T,
  COUNT(*) NF_FAT,
  SUM(CASE WHEN G.DT IS NOT NULL THEN 1 ELSE 0 END) COM_GWU_ENTREGA,
  CAST(100.0*SUM(CASE WHEN G.DT IS NOT NULL THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0) AS DECIMAL(5,1)) PCT_GWU,
  SUM(CASE WHEN G.PREV IS NOT NULL THEN 1 ELSE 0 END) COM_GWU_PREVISAO
FROM SF2010 F2
LEFT JOIN (SELECT GWU_FILIAL FIL, LTRIM(RTRIM(GWU_NRDC)) NRDC, LTRIM(RTRIM(GWU_SERDC)) SER,
                  MAX(NULLIF(GWU_DTENT,'')) DT, MAX(NULLIF(GWU_DTPENT,'')) PREV
           FROM GWU010 WHERE D_E_L_E_T_='' GROUP BY GWU_FILIAL, LTRIM(RTRIM(GWU_NRDC)), LTRIM(RTRIM(GWU_SERDC))) G
       ON G.FIL=F2.F2_FILIAL AND G.NRDC=LTRIM(RTRIM(F2.F2_DOC))
WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO >= @DE AND F2.F2_VALFAT > 0;
