-- FASE 0 · as TRES fontes de data de entrega, no universo decidido (faturamento, todas as filiais)
DECLARE @DE CHAR(8); SET @DE='20260201';
WITH SE1U AS (SELECT E1_FILIAL FIL, E1_NUM NUM, E1_PREFIXO PRE, MAX(NULLIF(E1_DTSAIDA,'')) DT
              FROM SE1010 WHERE D_E_L_E_T_='' GROUP BY E1_FILIAL,E1_NUM,E1_PREFIXO),
     GWUU AS (SELECT GWU_FILIAL FIL, LTRIM(RTRIM(GWU_NRDC)) NRDC,
                     MAX(NULLIF(GWU_DTENT,'')) DT, MAX(NULLIF(GWU_DTPENT,'')) PREV
              FROM GWU010 WHERE D_E_L_E_T_='' GROUP BY GWU_FILIAL, LTRIM(RTRIM(GWU_NRDC)))
SELECT LEFT(F2.F2_EMISSAO,6) ANOMES, COUNT(*) NF_FAT,
  CAST(100.0*SUM(CASE WHEN S.DT IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*) AS DECIMAL(5,1)) PCT_SE1_FINANC,
  CAST(100.0*SUM(CASE WHEN F2.F2_DTENTR<>'' THEN 1 ELSE 0 END)/COUNT(*) AS DECIMAL(5,1)) PCT_SF2,
  CAST(100.0*SUM(CASE WHEN G.DT IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*) AS DECIMAL(5,1)) PCT_GWU_REAL,
  CAST(100.0*SUM(CASE WHEN G.PREV IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*) AS DECIMAL(5,1)) PCT_GWU_PREV,
  CAST(100.0*SUM(CASE WHEN S.DT IS NOT NULL OR G.DT IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*) AS DECIMAL(5,1)) PCT_SE1_OU_GWU
FROM SF2010 F2
LEFT JOIN SE1U S ON S.FIL=F2.F2_FILIAL AND S.NUM=F2.F2_DOC AND S.PRE=F2.F2_SERIE
LEFT JOIN GWUU G ON G.FIL=F2.F2_FILIAL AND G.NRDC=LTRIM(RTRIM(F2.F2_DOC))
WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO >= @DE AND F2.F2_VALFAT > 0
GROUP BY LEFT(F2.F2_EMISSAO,6) ORDER BY ANOMES;

-- as datas concordam? (GWU real x SE1 financeiro)
DECLARE @DE2 CHAR(8); SET @DE2='20260201';
WITH SE1U AS (SELECT E1_FILIAL FIL, E1_NUM NUM, E1_PREFIXO PRE, MAX(NULLIF(E1_DTSAIDA,'')) DT
              FROM SE1010 WHERE D_E_L_E_T_='' GROUP BY E1_FILIAL,E1_NUM,E1_PREFIXO),
     GWUU AS (SELECT GWU_FILIAL FIL, LTRIM(RTRIM(GWU_NRDC)) NRDC, MAX(NULLIF(GWU_DTENT,'')) DT
              FROM GWU010 WHERE D_E_L_E_T_='' GROUP BY GWU_FILIAL, LTRIM(RTRIM(GWU_NRDC)))
SELECT COUNT(*) NF_COM_AS_DUAS,
  SUM(CASE WHEN S.DT=G.DT THEN 1 ELSE 0 END) IGUAIS,
  CAST(100.0*SUM(CASE WHEN S.DT=G.DT THEN 1 ELSE 0 END)/COUNT(*) AS DECIMAL(5,1)) PCT_IGUAIS,
  AVG(DATEDIFF(DAY, CONVERT(DATE,G.DT,112), CONVERT(DATE,S.DT,112))) MEDIA_DIAS_GWU_ATE_SE1
FROM SF2010 F2
JOIN SE1U S ON S.FIL=F2.F2_FILIAL AND S.NUM=F2.F2_DOC AND S.PRE=F2.F2_SERIE AND S.DT IS NOT NULL
JOIN GWUU G ON G.FIL=F2.F2_FILIAL AND G.NRDC=LTRIM(RTRIM(F2.F2_DOC)) AND G.DT IS NOT NULL
WHERE F2.D_E_L_E_T_='' AND F2.F2_EMISSAO >= @DE2 AND F2.F2_VALFAT > 0;
